name: Build
# This workflow is triggered on pushes to the repository.
on:
  push:
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.go-os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          go-os: linux
        - os:  macos-12
          go-os: darwin
        - os: windows-2022
          go-os: windows
          binary-suffix: .exe
    env:
      CGO_ENABLED: '0'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # fetch also tag info, relevant for detecting the version
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.1
    - name: Build binary
      run: make
    - name: Compress binary
      if: matrix.go-os != 'darwin'
      uses: svenstaro/upx-action@2.4.1
      with:
        file: oidc-token-ferry${{ matrix.binary-suffix }}
        args: --best
        strip: false
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: oidc-token-ferry_${{ matrix.go-os }}-amd64${{ matrix.binary-suffix }}
        path: oidc-token-ferry${{ matrix.binary-suffix }}
